spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          import_files: db_init.sql
  jackson:
    serialization:
      fail-on-empty-beans: false
springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    doc-expansion: none
    display-request-duration: true
    groups-order: ASC
    path: /api-docs
  show-actuator: true
  group-configs:            # add your groups here
    - group: all
      packagesToScan:
        - pl.envelo.meetek